/*
 * generated by Xtext
 */
package it.unibo.alchemist.language.protelis.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ProtelisDSLUiModule extends it.unibo.alchemist.language.protelis.ui.AbstractProtelisDSLUiModule {
	public ProtelisDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
