/*
 * generated by Xtext
 */
package it.unibo.alchemist.language.protelis;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ProtelisDSLRuntimeModule extends it.unibo.alchemist.language.protelis.AbstractProtelisDSLRuntimeModule {

}
